#ifndef _REFERENCES_HPP_
#define _REFERENCES_HPP_


#include "main.h"

//Controller joysticks
#define ANALOG_LX E_CONTROLLER_ANALOG_LEFT_X
#define ANALOG_LY E_CONTROLLER_ANALOG_LEFT_Y
#define ANALOG_RX E_CONTROLLER_ANALOG_RIGHT_X
#define ANALOG_RY E_CONTROLLER_ANALOG_RIGHT_Y

//Controller buttons
#define DIGIT_A E_CONTROLLER_DIGITAL_A
#define DIGIT_B E_CONTROLLER_DIGITAL_B
#define DIGIT_X E_CONTROLLER_DIGITAL_X
#define DIGIT_Y E_CONTROLLER_DIGITAL_Y
#define DIGIT_UP E_CONTROLLER_DIGITAL_UP
#define DIGIT_DOWN E_CONTROLLER_DIGITAL_DOWN
#define DIGIT_LEFT E_CONTROLLER_DIGITAL_LEFT
#define DIGIT_RIGHT E_CONTROLLER_DIGITAL_RIGHT
#define DIGIT_R1 E_CONTROLLER_DIGITAL_R1
#define DIGIT_R2 E_CONTROLLER_DIGITAL_R2
#define DIGIT_L1 E_CONTROLLER_DIGITAL_L1
#define DIGIT_L2 E_CONTROLLER_DIGITAL_L2


//Motor gearing
#define GEAR_RED E_MOTOR_GEARSET_36 //100 RPM 1800 Ticks
#define GEAR_GREEN E_MOTOR_GEARSET_18 //200 RPM 900 Ticks
#define GEAR_BLUE E_MOTOR_GEARSET_06 //600 RPM 300 Ticks
//4" wheel is about 13" per revolution


#endif
